### ISSUE TITLE
null reference when class map ignores all properties

### ISSUE THREAD

**Issue by spooky** [JoshClose/CsvHelper#1296]
```c#
class Foo
{
    public int MyProperty { get; set; }
}

class FooMap: ClassMap<Foo>
{
    public FooMap()
    {
        Map(x => x.MyProperty).Ignore();
    }
}

class Program
{
    static void Main(string[] args)
    {
        var x = new Foo
        {
            MyProperty = 123
        };

        using (var csv = new CsvWriter(Console.Out))
        {
            csv.Configuration.RegisterClassMap<FooMap>();
            csv.WriteRecords(new[] { x });
        }
    }
}
```

stack trace:
```text
Unhandled Exception: CsvHelper.WriterException: An unexpected error occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CsvHelper.Expressions.RecordWriter.Write[T](T record)
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
   --- End of inner exception stack trace ---
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
   at csvhspike.Program.Main(String[] args) in c:\code\sandbox\csvhspike\Program.cs:line 33
```

expected: empty output or a more user friendly exception

**Comment by JoshClose** [comment]
This is fixed and will be in version >= 12.2.2.
