### ISSUE TITLE
TypeConverterOptionsCache not thread safe

### ISSUE THREAD

**Issue by theezak** [JoshClose/CsvHelper#1320]
Receiving an error when running multiple CsvReaders at the same time.

CsvHelper.ReaderException: An unexpected error occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at CsvHelper.TypeConversion.TypeConverterOptionsCache.GetOptions(Type type)
   at CsvHelper.Expressions.ExpressionManager.CreateGetFieldExpression(MemberMap memberMap)
   at CsvHelper.Expressions.ExpressionManager.CreateMemberAssignmentsForMapping(ClassMap mapping, List`1 assignments)
   at CsvHelper.Expressions.ObjectRecordCreator.CreateCreateRecordDelegate(Type recordType)
   at CsvHelper.Expressions.RecordCreator.GetCreateRecordDelegate(Type recordType)
   at CsvHelper.Expressions.RecordCreator.Create(Type recordType)
   at CsvHelper.CsvReader.<GetRecords>d__65.MoveNext()
   --- End of inner exception stack trace ---
   at CsvHelper.CsvReader.<GetRecords>d__65.MoveNext()
   at System.Linq.EnumerableEx.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)

**Comment by tobyreid** [comment]
I'm also experiencing a similar issue - it appears to go away when i initialize a new version of the `Configuration` class each time when passing it into the `CsvReader`.

less optimal, but no errors...

**Comment by Quppa** [comment]
I got bitten by this, too - could a note be added to the docs about `Configuration` not being thread-safe? I've worked around the issue with `ThreadLocal`.

Repro: https://gist.github.com/Quppa/68e55e4df5883483ffa6ebcd00f78583

**Comment by JoshClose** [comment]
Please join the discussion here. https://github.com/JoshClose/CsvHelper/issues/1623

**Comment by JoshClose** [comment]
A lot has changed with how this works. I don't believe this is an issue anymore. If it is, let me know and I'll open it back up.
