### ISSUE TITLE
TypeConverterException when parsing integer as nullable double

### ISSUE THREAD

**Issue by peteburch223** [JoshClose/CsvHelper#1392]
Parsing a CSV row with the code below generates a TypeConverterException when the value `8` is encountered for a mapped field of type `double?`

```
CsvHelper.TypeConversion.TypeConverterException: The conversion cannot be performed.
    Text: '8'
    MemberType: System.Nullable`1[[System.Double, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
    TypeConverter: 'CsvHelper.TypeConversion.NullableConverter'
   at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at CsvHelper.TypeConversion.DoubleConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at CsvHelper.TypeConversion.NullableConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at lambda_method(Closure )
   at CsvHelper.Expressions.RecordCreator.Create[T]()
   at CsvHelper.CsvReader.GetRecord[T]()
   ... 
```
CsvHelper v12.1.2
System.Value.Tuple v4.6.25519.03
Built for .NET 4.6.1 as part of WCF service running under IIS

```csharp
        public List<T> Parse (string csvString)
        {
            using(MemoryStream memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(csvString)))
            using(StreamReader reader = new StreamReader(memoryStream))
            using(CsvReader csv = new CsvReader(reader))
            {
                csv.Configuration.RegisterClassMap<TM>();
                int rowCounter = 0;
                List<T> result = new List<T>();
                while (csv.Read())
                {
                    try
                    {
                        T record = csv.GetRecord<T>();
                        result.Add(record);
                    }
                    catch(Exception ex)
                    {
                        Log.Error($"Error processing row {rowCounter}", ex);
                    }
                    finally
                    {
                        rowCounter++;
                    }
                }
                return result;
            }
        }
```

**Comment by JoshClose** [comment]
Can you post sample CSV data that causes this to happen?
