### ISSUE TITLE
Easy way to write to a specific column and fill the rest with blanks

### ISSUE THREAD

**Issue by AnReZa** [JoshClose/CsvHelper#1419]
I need to write a CSV file with 78 columns, where only the first ten columns as well as index 53 and 54 must be filled. The other columns should be empty. My first idea was to use the Index attribute for that. However, it seems to work only for sorting, not for actually specifiying the column index.

Is there another method to achieve that without me having to define a class with 78 (mostly redundant) attributes?

**Comment by tomagb** [comment]
I'm also interested into this functionality. Is there any way to achieve it?

**Comment by dbc2** [comment]
Assuming you have some `ClassMap<TClass>` for your class, then when you are writing, in the constructor you can do 

    Map().Index(i).Constant("");

for column indices `i` for which you want to output a constant empty value.  However, when reading you will need to construct the  class map without the constant columns as CsvReader will throw an error when a column is not mapped to a class member *even if it is constant*.

See: [this answer](https://stackoverflow.com/a/67217679/3744182) to [Write data in specific position](https://stackoverflow.com/q/67216668/3744182).

**Comment by JoshClose** [comment]
@dbc2 That's pretty clever!

**Comment by JoshClose** [comment]
I could probably change the reader so if there is no property mapped, it won't throw.

**Comment by dbc2** [comment]
Thanks for the reply!

I'm not the original requestor, but I do think that makes sense for constant columns if it's easy. Having to bind constant columns to a dummy member is a little awkward.

Demo here: https://dotnetfiddle.net/uLKTJ1.

Traceback is:

```
 ---> System.InvalidOperationException: Member is not a property or a field.
   at CsvHelper.Expressions.ExpressionManager.CreateGetFieldExpression(MemberMap memberMap)
   at CsvHelper.Expressions.ExpressionManager.CreateMemberAssignmentsForMapping(ClassMap mapping, List`1 assignments)
   at CsvHelper.Expressions.ObjectRecordCreator.CreateCreateRecordDelegate(Type recordType)
   at CsvHelper.Expressions.RecordCreator.GetCreateRecordDelegate(Type recordType)
   at CsvHelper.Expressions.RecordCreator.Create[T]()
   at CsvHelper.Expressions.RecordManager.Create[T]()
```
Specifically `memberMap.Data.Member.MemberType` throws when `Member` is not a `FieldInfo` or `PropertyInfo`.
