### ISSUE TITLE
Error Reading Decimal Value From Quoted String With Comma Thousands Separator (en-AU)

### ISSUE THREAD

**Issue by brendonwm** [JoshClose/CsvHelper#1480]
**Describe the bug**
I get an exception with error message "CsvHelper.TypeConversion.TypeConverterException: The conversion cannot be performed." when attempting to read a decimal value from a quoted string with a comma for thousands separator. The specified culture was en-AU (have also tried InvariantCulture). I'm not sure if this issue is related to using a ClassMap or not.

For example, Excel may save a CSV like this and attempting to parse the decimal into a decimal property fails. If the comma is removed, it works.
Heading Value Name
"1,000.00000000000"

**To Reproduce**
Simplified standalone sample code as follows, Visual Studio solution attached in [CsvHelperRepro.zip](https://github.com/JoshClose/CsvHelper/files/4372577/CsvHelperRepro.zip).

```
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using CsvHelper;
using CsvHelper.Configuration;

namespace ConsoleApp1
{
    class Program
    {
        private static readonly string ExampleCsvData = "Value To Read" + Environment.NewLine + "\"1,000.00000000000\"";    // Doesn't work.
        //private static readonly string ExampleCsvData = "Value To Read" + Environment.NewLine + "\"1000.00000000000\"";    // Works.

        static void Main()
        {
            Console.WriteLine("Push enter to exit");
            try
            {
                ReadMyData(ExampleCsvData).Wait();
            }
            catch (AggregateException ex)
            {
                foreach (var exInnerException in ex.InnerExceptions)
                {
                    Console.WriteLine(exInnerException);
                }
            }
            Console.ReadLine();
        }

        private static async Task<IList<MyData>> ReadMyData(string csvData)
        {
            var results = new List<MyData>();

            using var reader = new StringReader(csvData);
            using var csv = new CsvReader(reader, new CultureInfo("en-AU"));
            csv.Configuration.RegisterClassMap<MyDataMap>();
            await foreach (var record in csv.GetRecordsAsync<MyData>())
            {
                Console.WriteLine($"Read record: {nameof(MyData)}.{nameof(MyData.ValueToRead)}: {record.ValueToRead}");
                results.Add(record);
            }

            return results;
        }
    }

    public class MyData
    {
        public decimal ValueToRead { get; set; }
    }

    public sealed class MyDataMap : ClassMap<MyData>
    {
        public MyDataMap()
        {
            Map(m => m.ValueToRead).Name("Value To Read");
        }
    }
}
```

**Expected behavior**
Expected decimal value to parse without error.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/22039891/77377426-2da61500-6dc7-11ea-8efe-374b55a90444.png)

**Additional context**
Exception detail:
CsvHelper.TypeConversion.TypeConverterException: The conversion cannot be performed.
    Text: '1,000.00000000000'
    MemberType: System.Decimal
    TypeConverter: 'CsvHelper.TypeConversion.DecimalConverter'
   at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at CsvHelper.TypeConversion.DecimalConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData)
   at lambda_method(Closure )
   at CsvHelper.Expressions.RecordCreator.Create[T]()
   at CsvHelper.Expressions.RecordManager.Create[T]()
   at CsvHelper.CsvReader.GetRecordsAsync[T]()+MoveNext()
   at CsvHelper.CsvReader.GetRecordsAsync[T]()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at ConsoleApp1.Program.ReadMyData(String csvData) in C:\Dev\CsvHelperRepro\CsvHelperRepro\ConsoleApp1\Program.cs:line 40
   at ConsoleApp1.Program.ReadMyData(String csvData) in C:\Dev\CsvHelperRepro\CsvHelperRepro\ConsoleApp1\Program.cs:line 40

**Comment by brendonwm** [comment]
I can work around this by replacing my **_Map_** call as follows:
```
Map(m => m.ValueToRead).ConvertUsing(d =>
                decimal.Parse(d.GetField("Value To Read"), CultureInfo.GetCultureInfo("en-AU")));
```

**Comment by JoshClose** [comment]
If I change the number styles in the mapping to `NumberStyles.Number` it works. Maybe this should be the default for `decimal`. The default is currently `NumberStyles.Float`.

**Comment by JoshClose** [comment]
```cs
Map(m => m.ValueToRead).Name("Value To Read").TypeConverterOption.NumberStyles(NumberStyles.Number);
```

**Comment by JoshClose** [comment]
I just pushed version 15.0.3 to NuGet that has the default changed to `NumberStyles.Number` which should fix your issue.
