### ISSUE TITLE
Non-reproducible null ref exception

### ISSUE THREAD

**Issue by fayilt** [JoshClose/CsvHelper#1552]
Hi,

I got the below exception, but it only happened once and I can't reproduce it now:
```
CsvHelper.ReaderException: An unexpected error occurred.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/Dictionary.cs:line 371
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/Dictionary.cs:line 906
   at CsvHelper.TypeConversion.TypeConverterOptionsCache.GetOptions(Type type)
   at CsvHelper.Expressions.ExpressionManager.CreateGetFieldExpression(MemberMap memberMap)
   at CsvHelper.Expressions.ExpressionManager.CreateMemberAssignmentsForMapping(ClassMap mapping, List`1 assignments)
   at CsvHelper.Expressions.ObjectRecordCreator.CreateCreateRecordDelegate(Type recordType)
   at CsvHelper.Expressions.RecordCreator.GetCreateRecordDelegate(Type recordType)
   at CsvHelper.Expressions.RecordCreator.Create[T]()
   at CsvHelper.Expressions.RecordManager.Create[T]()
   at CsvHelper.CsvReader.GetRecords[T]()+MoveNext()
   --- End of inner exception stack trace ---
   at CsvHelper.CsvReader.GetRecords[T]()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs:line 92
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) in /_/src/System.Linq/src/System/Linq/ToCollection.cs:line 27
```

The file was copied over network, and it's possible it got corrupted, but I can't prove it now and was wondering if you can shed some light on this error based on what you see in the stack trace?

Loading the same file again worked fine btw.

Here's the code:
```
                using (var reader = new StreamReader(File.OpenRead(fileName), _encoding))
                {
                    var csv = new CsvReader(reader, _csvConfiguration);
                    var records = csv.GetRecords<CsvVolRow>().ToList();
                    ...
                }
```

Can you suggest the possible reasons by looking at the stack trace?

Thanks very much in advance

**Comment by bazarniy** [comment]
```
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/Dictionary.cs:line 371
at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/Dictionary.cs:line 906
```
Looks like read and write from in same time from multiple threads. Simple Dictionaty is not thread safe. There are a lot of similar stactraces at stackoverflow (https://stackoverflow.com/questions/2283455/how-is-this-dictionarytkey-tvalue-exception-possible)

Simpliest way is to change Dictionary to ConcurrentDictionary inside CsvHelper library

**Comment by JoshClose** [comment]
Please join the discussion here. https://github.com/JoshClose/CsvHelper/issues/1623
