### ISSUE TITLE
Raise Header with name 'timeStamp' was not found

### ISSUE THREAD

**Issue by davzucky** [JoshClose/CsvHelper#1601]
**Describe the bug**
I'm using CsvHelper to write and read csv. However when I want the read the csv file just written I'm getting the error
```
Header with name 'timeStamp' was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.
```
The header is there, however the field is name 'TimeStamp' and not 'timeStamp'. Look like they are a discripency on the casing between the writer and reader

**To Reproduce**
Run the following unit test
```
public class CsvHelperTestError
    {
        public class Candle
        {
            public DateTime TimeStamp { get; }
            public Decimal? Open { get; }
            public Decimal? High { get; }
            public Decimal? Low { get; }
            public Decimal? Close { get; }
            public Decimal? Volume { get; }
            public Decimal? Trades { get; }

            public Candle(DateTime timeStamp, decimal? open, decimal? high, decimal? low, decimal? close, decimal? volume, decimal? trades)
            {
                TimeStamp = timeStamp;
                Open = open;
                High = high;
                Low = low;
                Close = close;
                Volume = volume;
                Trades = trades;
            }
        }

        [Fact]
        public void TestWriteAndReadCsv()
        {
            var records = new List<Candle>()
            {
                new Candle(new DateTime(2010, 1, 1), 1000, 1100, 9900, 1050, null, null),
                new Candle(new DateTime(2010, 1, 1), 1050, 1100, 9900, 1050, 1, 3),
            };
            var rootFolder = Path.Join(Path.GetTempPath(), Guid.NewGuid().ToString(), "XBTUSD", "1d");
            var filePath = Path.Join(rootFolder, "daily.csv");
            
            Directory.CreateDirectory(rootFolder);

            using (var writer = new StreamWriter(filePath))
            {
                using (var csvWriter = new CsvWriter(writer, CultureInfo.InvariantCulture))
                {
                    csvWriter.WriteRecords(records);
                }
            }
            
            using (var reader = new StreamReader(filePath))
            {
                using (var csvReader = new CsvReader(reader, CultureInfo.InvariantCulture))
                {
                    var resultRecords = csvReader.GetRecords<Candle>().ToList();
                    resultRecords.Should().HaveCount(records.Count);
                }
            }
        }
    }
```

**Expected behavior**
Been able to read the data just written

**Screenshots**
```
dotnet test --filter "FullyQualifiedName~CsvHelperTestError"
Test run for /home/dzucker/git/Hyperwave.3commas/src/Hyperwave.Shared.Tests/bin/Debug/netcoreapp3.1/Hyperwave.Shared.Tests.dll(.NETCoreApp,Version=v3.1)
Test run for /home/dzucker/git/Hyperwave.3commas/src/Hyperwave.Bitmex.Tests/bin/Debug/netcoreapp3.1/Hyperwave.Bitmex.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Test run for /home/dzucker/git/Hyperwave.3commas/src/Hyperwave.Core.Tests/bin/Debug/netcoreapp3.1/Hyperwave.Core.Tests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
No test matches the given testcase filter `FullyQualifiedName~CsvHelperTestError` in /home/dzucker/git/Hyperwave.3commas/src/Hyperwave.Shared.Tests/bin/Debug/netcoreapp3.1/Hyperwave.Shared.Tests.dll

No test matches the given testcase filter `FullyQualifiedName~CsvHelperTestError` in /home/dzucker/git/Hyperwave.3commas/src/Hyperwave.Bitmex.Tests/bin/Debug/netcoreapp3.1/Hyperwave.Bitmex.Tests.dll

[xUnit.net 00:00:01.89]     Hyperwave.Core.Tests.Actors.CsvHelperTestError.TestWriteAndReadCsv [FAIL]
  X Hyperwave.Core.Tests.Actors.CsvHelperTestError.TestWriteAndReadCsv [161ms]
  Error Message:
   CsvHelper.HeaderValidationException : Header with name 'timeStamp' was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.
  Stack Trace:
     at CsvHelper.Configuration.ConfigurationFunctions.HeaderValidated(Boolean isValid, String[] headerNames, Int32 headerNameIndex, ReadingContext context)
   at CsvHelper.CsvReader.ValidateHeader(ClassMap map)
   at CsvHelper.CsvReader.ValidateHeader(Type type)
   at CsvHelper.CsvReader.ValidateHeader[T]()
   at CsvHelper.CsvReader.GetRecords[T]()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Hyperwave.Core.Tests.Actors.CsvHelperTestError.TestWriteAndReadCsv() in /home/dzucker/git/Hyperwave.3commas/src/Hyperwave.Core.Tests/Actors/CsvHelperTestError.cs:line 61

Test Run Failed.
Total tests: 1
     Failed: 1
 Total time: 3.8972 Seconds
/usr/share/dotnet/sdk/3.1.403/Microsoft.TestPlatform.targets(32,5): error MSB4181: The "Microsoft.TestPlatform.Build.Tasks.VSTestTask" task returned false but did not log an error. [/home/dzucker/git/Hyperwave.3commas/src/Hyperwave.Core.Tests/Hyperwave.Core.Tests.csproj]

```
**Additional context**
Running on Dotnet core 3.1 on Linux

**Comment by AltruCoder** [comment]
I believe you can find an answer to the issue here https://github.com/JoshClose/CsvHelper/issues/1078

**Comment by davzucky** [comment]
Thank you @AltruCoder for the fast reply. Indeed this is the same problem. I confirm that changing the casing of the input constructor is working. As I dont like that, I will explore the usage ClassMap
