### ISSUE TITLE
An unexpected error occurred. InvalidCastException

### ISSUE THREAD

**Issue by Harbring** [JoshClose/CsvHelper#1609]
Hi Josh, superb work!

I'm CsvHelper NET4.8 and get the above error. This is what the debugger says:

at CsvHelper.Expressions.RecordCreator.Create[T]() in C:\Users\micha\Desktop\CsvHelper-master\src\CsvHelper\Expressions\RecordCreator.cs:line 43
   at CsvHelper.Expressions.RecordManager.Create[T]() in C:\Users\micha\Desktop\CsvHelper-master\src\CsvHelper\Expressions\RecordManager.cs:line 47
   at CsvHelper.CsvReader.<GetRecords>d__63`1.MoveNext() in C:\Users\micha\Desktop\CsvHelper-master\src\CsvHelper\CsvReader.cs:line 1085

I'm using it from a VB-NET project with a class property typed Integer? (a nullable int). When I just use Integer everything is fine. Any suggestions?

Regards,
Michael

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JoshClose** [comment]
Can you give a small unit test like example that demonstrates the issue?

**Comment by Harbring** [comment]
[ConsoleApp1.zip](https://github.com/JoshClose/CsvHelper/files/5488742/ConsoleApp1.zip)

Here you are.

**Comment by JoshClose** [comment]
Your type converter is returning an `enum` and your property is an `int?`.

**Comment by Harbring** [comment]
Historical database format, not changeable.

**Comment by JoshClose** [comment]
I'm confused. You're trying to do this:

```cs
foo.A = SomeEnum.One;
```

It's just not possible. You can't assign an enum to an int.
