### ISSUE TITLE
ArgumentNullException in Version > 17.0.1

### ISSUE THREAD

**Issue by mrdavidkovacs** [JoshClose/CsvHelper#1631]
**Describe the bug**
The following class has been serialized with version 15.0.10 and 17.0.1 before without problems:

```
public class ExportInformation
{
    public ExportInformation(string name, string[] information)
    {
        this.Name = name;
        this.InformationItems = information;
        this.InformationAsString = string.Join(", ", information);
    }

    [Name("Description")]
    public string Name { get; set; }

    [Ignore]
    public string[] InformationItems { get; set; }

    [Name("Information")]
    public string InformationAsString{ get; set; }
}
```

With Version 18.0.0 the following exception is thrown:

```
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at CsvHelper.Configuration.ClassMap.ApplyAttributes(ParameterMap parameterMap)
   at CsvHelper.Configuration.ClassMap.AutoMapConstructorParameters(ClassMap map, CsvConfiguration configuration, LinkedList`1 mapParents, Int32 indexStart)
   at CsvHelper.Configuration.ClassMap.AutoMapConstructorParameters(ClassMap map, CsvConfiguration configuration, LinkedList`1 mapParents, Int32 indexStart)
   at CsvHelper.Configuration.ClassMap.AutoMap(CsvConfiguration configuration)
   at CsvHelper.Configuration.CsvConfiguration.AutoMap(Type type)
   at CsvHelper.CsvWriter.WriteHeader(Type type)
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
```

**To Reproduce**
See class above.

**Expected behavior**
This should work again.

**Screenshots**
Not applicable

**Additional context**
Maybe this issue is related with #1621 as the IgnoreAttribute does not implement the IParameterMapper interface.

**Comment by JoshClose** [comment]
Yes. I'm working on that. I'm adding in all the attributes for constructors though.

**Comment by mikkelbu** [comment]
@JoshClose This should also be closed as part of the 19.0.0 release.

**Comment by JoshClose** [comment]
Thanks.

**Comment by mrdavidkovacs** [comment]
Should be fixed with 6a4fd9a8b5fabc6276aaea51d0bffbfe824bc01c.

**Comment by mrdavidkovacs** [comment]
This is not resolved in v19.0.0

**Comment by JoshClose** [comment]
Since you don't have a parameterless constructor, you need to put the attributes on the constructor argument. Since you're writing and not reading, this should work. It seems name works still. I'll look into why.

**Comment by JoshClose** [comment]
Actually, no it shouldn't. It's trying to map a `string[]` and fails. You need to put the `[Ignore]` attribute on the information parameter and it'll work.

The other options is to not let it map the constructor.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
	ShouldUseConstructorParameters = (type) => false,
};
```
