### ISSUE TITLE
_csvWriter.Context.AutoMap<XXXX>() throwing exception

### ISSUE THREAD

**Issue by EricZimmerman** [JoshClose/CsvHelper#1677]
Older versions, prior to needing to use Context vs Configuration, did not have this issue

after upgrading to 21.2.1, this line

   var foo = _csvWriter.Context.AutoMap<EventRecord>();

now throws this error:

System.ArgumentNullException: 'Value cannot be null.
Parameter name: source'

stack:
```
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CsvHelper.Configuration.ClassMap.AutoMapConstructorParameters(ClassMap map, CsvContext context, LinkedList`1 mapParents, Int32 indexStart)
   at CsvHelper.Configuration.ClassMap.AutoMapConstructorParameters(ClassMap map, CsvContext context, LinkedList`1 mapParents, Int32 indexStart)
   at CsvHelper.Configuration.ClassMap.AutoMapConstructorParameters(ClassMap map, CsvContext context, LinkedList`1 mapParents, Int32 indexStart)
   at CsvHelper.Configuration.ClassMap.AutoMap(CsvContext context)
   at CsvHelper.CsvContext.AutoMap[T]()
   at EvtxECmd.Program.Main(String[] args) in D:\Code\evtx\EvtxECmd\Program.cs:line 442
```

**source for EventRecord**
https://github.com/EricZimmerman/evtx/blob/master/evtx/EventRecord.cs

This class does have a few IgnoreDataMember attributes, but even removing them does not fix things

**source where error happens**
https://github.com/EricZimmerman/evtx/blob/master/EvtxECmd/Program.cs#L442

**Expected behavior**
It should work like the previous version =)

**Comment by EricZimmerman** [comment]
Reverting to 17.0.1 fixes this situation and it runs fine

**Comment by JoshClose** [comment]
Versions 17 and 18 introduced the ability to put attributes on constructor arguments. Since you only have a non-parameterless constructor, it's mapping that.

It will try and map all the parameters `EventRecord(BinaryReader recordData, int recordPosition, ChunkInfo chunk)`, which isn't going to work for at least `BinaryReader`.

There are a couple things you can do. You can drop an `[Ignore]` attribute on the parameters giving you issues. The other option is to tell it to not map the constructor at all, which I'm guessing is better in your case.

```cs
ShouldUseConstructorParameters = _ => false,
```

**Comment by EricZimmerman** [comment]
confirming this works as expected:

```
   var opt = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
    ShouldUseConstructorParameters = _ => false
    };

  _csvWriter = new CsvWriter(_swCsv,opt);
```

**Comment by JoshClose** [comment]
Awesome! And thanks for the Open Collective donation!

**Comment by EricZimmerman** [comment]
sure thing. this is a great project!
