### ISSUE TITLE
Unhandled Exception: System.TypeLoadException: Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

### ISSUE THREAD

**Issue by GanZhiXiong** [JoshClose/CsvHelper#2068]
```csharp
Unhandled Exception: System.TypeLoadException: Could not load type 'System.ValueTuple`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at CsvHelper.CsvReader..ctor(IParser parser)
   at CsvHelper.CsvReader..ctor(TextReader reader, CultureInfo culture, Boolean leaveOpen)
```

**Comment by FrankNanninga** [comment]
I've seen this sort of error a couple of times - my guess is that installing .NET Framework 4.7.2 (or higher) on the server should do the trick.

**Comment by JoshClose** [comment]
@FrankNanninga Do you know why that would be?

I have these settings for `net45`.
```xml
<!-- .NET 4.5 -->
<ItemGroup Condition="'$(TargetFramework)' == 'net45'">
	<PackageReference Include="Microsoft.CSharp" Version="4.3.0" />
	<PackageReference Include="System.Memory" Version="4.5.0" />
	<PackageReference Include="System.ValueTuple" Version="4.3.0" />
</ItemGroup>
```

It look like `net45` is covered.
https://www.nuget.org/packages/System.ValueTuple/4.3.0#supportedframeworks-body-tab
