### ISSUE TITLE
Problem with CultureInfo: "CsvHelper.TypeConversion.CsvTypeConverterException : The conversion cannot be performed."

### ISSUE THREAD

**Issue by okas** [JoshClose/CsvHelper#290]
Hi,
I need to use different culture from CurrentCulture, so is set it up in CsvConfiguration instance. Then I use this instance for CsvReader creation in constructor call.
Turns out that this culture is not used during mapping, at least in one specific case.
My (partial) mapping code:

``` c#
public abstract class StatementRowMappingBase : CsvClassMap<StatementRowDTO>
    {
        protected void CreateCommonMapping(BankStatementBase statement)
        {
            base.Map(m => m.Date).Name(statement.DateField);
            base.Map(m => m.Description).Name(statement.DescriptionField);
            base.Map(m => m.Amount)
                .Name(statement.AmountField)
                .ConvertUsing(row => Math.Abs(row.GetField<decimal>(statement.AmountField)));
        }
    }
```

Decimal Amount filed cannot be converted. I looked into source code and I can pinpoint code that uses wrong Culture:
TypeConverterOptionsFactory.GetOptions(Type), line 93.
Returned TypeConferterOptions for Decimal type has Culture that is always equal to System.Globalization.CultureInfo.CurrentCulture. I my case it is “et-EE”. But I need to use Invariant Culture.
Here is stack trace :

```
CsvHelper.TypeConversion.CsvTypeConverterException : The conversion cannot be performed.
   at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(TypeConverterOptions options, String text) in DefaultTypeConverter.cs: line 45   
   at CsvHelper.TypeConversion.DecimalConverter.ConvertFromString(TypeConverterOptions options, String text) in c:\Projects\CsvHelper\src\CsvHelper\TypeConversion\DecimalConverter.cs: line 30
   at CsvHelper.CsvReader.GetField(Int32 index, ITypeConverter converter) in CsvReader.cs: line 553
   at MVC.BL.Infrastructure.CSV.StatementRowMappingBase.<>c__DisplayClass1.<CreateCommonMapping>b__0(ICsvReaderRow row) in StatementRowMappingBase.cs: line 17
   at lambda_method(Closure)   at CsvHelper.CsvReader.GetRecord() in CsvReader.cs: line 877
   at MVC.BL.Infrastructure.CSV.CsvReaderExtenstions.<GetRecords>d__0`1.MoveNext() in CsvReaderExtenstions.cs: line 24
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList(IEnumerable`1 source)
   at MVC.Tests.BankAccountStatement.CsvParserComponentsTests.CanLoadPreFilterRecords_FromCorrectCsv_ShouldPass(CsvConfiguration csvConfiguration, BankStatementComplex definition, TextReader textReader, Int32 countResult) in CsvParserComponentsTests.cs: line 150
```

CsvHelper version is 2.7.0 (from Nuget)

**Comment by shift-evgeny** [comment]
It seems to me like this can be fixed simply by not caching "new TypeConverterOptions()" in GetOptions(). Submitted PR #546 for this.
