### ISSUE TITLE
Parsing Quoted Guids

### ISSUE THREAD

**Issue by rhettc** [JoshClose/CsvHelper#330]
In the file I am parsing all fields are quoted with double quotes. I have mapped a guid field as part of a referenced class mapping. 

It looks like the quotes are being included in the string that is parsed to form the Guid.

## Data ##
```
"task_time","attach_activity_id_xfer.guid","attach_activity_id_xfer.seq","attach_activity_id.guid","attach_activity_id.seq"
"85754412","18ECB6A4-3717-4FD7-8CC3-FCEAA3241D82","0","BB3DAD9B-2EE9-4604-91F2-879FF845AAD0","1"
```
## Classes ##
``` c#
 public AttachActivityMap()
        {
            Map(m => m.Guid).Index(0);
            Map(m => m.Sequence).Index(1);

        }

public ExtendedEventMap()
        {
            // fields omitted for brevity
            Map(m => m.TaskTime).Name("task_time");
            References<AttachActivityMap>(m => m.AttachedActivityXfer);
            References<AttachActivityMap>(m => m.AttachedActivity);
        }
```

## Resulting Exception ##
```
System.FormatException was unhandled
  _HResult=-2146233033
  _message=Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
  HResult=-2146233033
  IsTransient=false
  Message=Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
  Source=mscorlib
  StackTrace:
       at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
       at System.Guid.TryParseGuidWithNoStyle(String guidString, GuidResult& result)
       at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
       at System.Guid..ctor(String g)
       at CsvHelper.TypeConversion.GuidConverter.ConvertFromString(TypeConverterOptions options, String text) in c:\Projects\CsvHelper\src\CsvHelper\TypeConversion\GuidConverter.cs:line 28
       at lambda_method(Closure )
       at CsvHelper.CsvReader.CreateRecord[T]() in c:\Projects\CsvHelper\src\CsvHelper\CsvReader.cs:line 1260
       at CsvHelper.CsvReader.<GetRecords>d__1`1.MoveNext() in c:\Projects\CsvHelper\src\CsvHelper\CsvReader.cs:line 939
       at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
       at CsvConsole.Program.Main(String[] args) in c:\dev\sql-event-viewer\SqlEventViewer\CsvConsole\Program.cs:line 27
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

## Snippet to reproduce in LINQPad
```
new Guid("\"18ECB6A4-3717-4FD7-8CC3-FCEAA3241D82\"")
```

**Comment by rhettc** [comment]
Updating the classes I'm using since I also misunderstood how Referenced types worked. 

``` c#
  public class AttachActivityMap : CsvClassMap<AttachActivity>
    {
        public AttachActivityMap()
        {
            Map(m => m.Guid).Name("attach_activity_id.guid");
            Map(m => m.Sequence).Name("attach_activity_id.seq");

        }
        
    }

    public class AttachActivityXferMap : CsvClassMap<AttachActivity>
    {
        public AttachActivityXferMap()
        {
            Map(m => m.Guid).Name("attach_activity_id_xfer.guid");
            Map(m => m.Sequence).Name("attach_activity_id_xfer.seq");

        }

    }
```

Since the CSV is generated with dot delimited headers it would have been cool if it could have utilized this when parsing. 

I wonder if you would consider pull requests for something like that as well as a feature to support automatically mapping snake case headers to camel case properties. So that users wouldn't have to do this
``` c#
Map(m => m.CpuTime).Name("cpu_time");
// instead they would simply 
Map(m => m.CpuTime);
```

**Comment by JoshClose** [comment]
So do you now have the GUID issue anymore then? Is this just a feature request to automatically treat different types of header name formats?

**Comment by rhettc** [comment]
I no longer have the issue with the Guid fields.

Thanks, I was overlooking that the issue I thought I found was just a result of the way I misunderstood Reference Mapping. Makes sense. 

If you are interested in discussing the features I mentioned, let me know.

**Comment by JoshClose** [comment]
Yeah, I think that would be a good feature. You can already do references automatically with a prefix. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/CsvConfiguration.cs#L383
