### ISSUE TITLE
`The conversion cannot be performed` when `GetRecords` using `Nullable<DateTimeOffset>`

### ISSUE THREAD

**Issue by euyuil** [JoshClose/CsvHelper#387]
I get `The conversion cannot be performed` when `GetRecords` using `DateTimeOffset?` as a property of the record.

The assembly was obtained from NuGet. The version is `2.13.0.0`.

This is my code:

    internal class Program
    {
        internal class Entity
        {
            public string Title { get; set; }

            public DateTimeOffset? Time { get; set; }
        }

        internal static string ToCsvString(Entity[] entities)
        {
            using (var memoryStream = new MemoryStream())
            using (var streamWriter = new StreamWriter(memoryStream))
            {
                using (var csvWriter = new CsvWriter(streamWriter))
                {
                    csvWriter.WriteRecords(entities);
                }

                using (var shadowStream = new MemoryStream(memoryStream.ToArray()))
                using (var streamReader = new StreamReader(shadowStream))
                {
                    return streamReader.ReadToEnd();
                }
            }
        }

        internal static void Main(string[] args)
        {
            var entities = new[]
            {
                new Entity { Title = "Foo", Time = DateTimeOffset.Now },
                new Entity { Title = "Bar", Time = null }
            };

            var content = ToCsvString(entities);

            Console.WriteLine(content);
            
            using (var memoryStream = new MemoryStream())
            using (var streamWriter = new StreamWriter(memoryStream))
            using (var streamReader = new StreamReader(memoryStream))
            using (var csvReader = new CsvReader(streamReader))
            {
                streamWriter.Write(content);
                streamWriter.Flush();
                memoryStream.Position = 0;
                var records = csvReader.GetRecords<Entity>().ToArray();
                // Exception here.
            }
        }
    }

This is the detail of the exception:

    CsvHelper.TypeConversion.CsvTypeConverterException was unhandled
      HResult=-2146233088
      Message=The conversion cannot be performed.
      Source=CsvHelper
      StackTrace:
           at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(TypeConverterOptions options, String text) in c:\Projects\CsvHelper\src\CsvHelper\TypeConversion\DefaultTypeConverter.cs:line 45
           at CsvHelper.TypeConversion.NullableConverter.ConvertFromString(TypeConverterOptions options, String text) in c:\Projects\CsvHelper\src\CsvHelper\TypeConversion\NullableConverter.cs:line 69
           at lambda_method(Closure )
           at CsvHelper.CsvReader.CreateRecord[T]() in c:\Projects\CsvHelper\src\CsvHelper\CsvReader.cs:line 1282
           at CsvHelper.CsvReader.<GetRecords>d__1`1.MoveNext() in c:\Projects\CsvHelper\src\CsvHelper\CsvReader.cs:line 945
           at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
           at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
           at CsvHelperTest.Program.Main(String[] args) in c:\Users\Yue\Documents\Visual Studio 2013\Projects\CsvHelperTest\Program.cs:line 56
           at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
           at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
           at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
           at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.ThreadHelper.ThreadStart()
      InnerException: 

Output of `ex.Data`:

    Row: '2' (1 based)
    Type: 'CsvHelperTest.Program+Entity'
    Field Index: '1' (0 based)
    Field Name: 'Time'
    Field Value: '5/14/2015 10:02:30 PM +08:00'

Console output:

    Title,Time
    Foo,5/14/2015 10:03:46 PM +08:00
    Bar,

**Comment by JoshClose** [comment]
This is fixed. The `DateTimeOffsetConverter` wasn't being added to the default list of converters.
