### ISSUE TITLE
Exceptions should contain helpful details

### ISSUE THREAD

**Issue by dsaf** [JoshClose/CsvHelper#534]
Example:

```
CsvHelper.TypeConversion.CsvTypeConverterException occurred
  HResult=-2146233088
  Message=The conversion cannot be performed.
  Source=CsvHelper
  StackTrace:
       at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(TypeConverterOptions options, String text)
       at CsvHelper.TypeConversion.EnumConverter.ConvertFromString(TypeConverterOptions options, String text)
       at lambda_method(Closure )
       at CsvHelper.CsvReader.CreateRecord[T]()
       at CsvHelper.CsvReader.<GetRecords>d__63`1.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
...
```

No idea what line, what column, what value caused the problem.

Suggested message:

```
Could not perform value conversion while parsing column 5 of row 12: "ValueCausingError".
```

**Comment by dsaf** [comment]
I have found the ```ExceptionHelper.AddExceptionDataMessage```. There is probably a good reason for using ```Exception.Data``` but it's quite user/log unfriendly.

**Comment by dsaf** [comment]
This is what I came up with:

```
try
{
}
catch (CsvHelperException ex)
{
    var details = ex.Data.Values.Cast<string>().ToDelimitedString(". ").Trim().Replace(Environment.NewLine, ". ");
    throw new BusinessDataException($"Failed to read Business Objects. {details}.", ex);
}
```

**Comment by JoshClose** [comment]
There is a feature request to change this to have information on the exception itself instead of inside data.

**Comment by dsaf** [comment]
Cool, thanks.

**Comment by JoshClose** [comment]
It's kind of a pain right now, and don't even remember why I went that route. Someone made a good argument. I think it's been proven through usage that it's not a good idea though.
