### ISSUE TITLE
3.0.0-beta7: Mapping of constants

### ISSUE THREAD

**Issue by dmitry-azaraev** [JoshClose/CsvHelper#661]
If you try to register next mapping:

```csharp
        class MyClassMap : CsvClassMap<MyClass>
        {
            public MyClassMap()
            {
                Map(m => m.Id);
                Map().Constant("Hello, world!");
                Map(m => m.Value);
            }
        }
```

It will fail with exception:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CsvHelper.ReflectionHelper.CreateInstance(Type type, Object[] args)
   at CsvHelper.ReflectionHelper.CreateInstance[T](Object[] args)
   at CsvHelper.Configuration.CsvConfiguration.RegisterClassMap[TMap]()
```

But next code work (so can be workarounded by using exact indexes):

```csharp
        class MyClassMap : CsvClassMap<MyClass>
        {
            public MyClassMap()
            {
                Map(m => m.Id);
                Map(m => m.Value);
                Map().Constant("Hello, world!");
            }
        }
```

**Comment by JoshClose** [comment]
I'll look into this. Looks like i only have the second scenario covered in unit tests.

**Comment by JoshClose** [comment]
Fixed and will be in next pre-release.
