### ISSUE TITLE
Semicolon as delimiter not working

### ISSUE THREAD

**Issue by franelj** [JoshClose/CsvHelper#674]
Hi !

So, I've been trying to use CsvHelper to parse some CSV files (obviously) and I am currently encountering a pretty strange issue about delimiters.

If my delimiter is a comma, it works perfectly fine ; however, the files I need to parse are using a semicolon as delimiter, and the parser seems to be unable to split the rows when I set csv.Configuration.Delimiter to ";".
The problem seems to be specific to the semicolon because I also tested with "|" and "~" as delimiters, and it also works perfectly.
**UPDATE :** just tried with ":" as delimiter and it is not working.

All rows of my files are like this : 
`1;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;somestring;somestring`
I do not have any other semicolon than delimiters in a row.

Some code, in case you need it : 

**In my controller :** 
```
MemoryStream vouchersFile = await blobClient.GetFileFromBlob("post", fileVoucherRequest.VoucherFilePath);
TextReader tr = new StreamReader(vouchersFile);
var csvReader = new CsvReader(tr);

csvReader.Configuration.Delimiter = ";"; // If commented, use comma as default
csvReader.Configuration.RegisterClassMap<VoucherFileMap>();
csvReader.Configuration.HasHeaderRecord = false;
List<VoucherFile> vouchers = new List<VoucherFile>();
vouchersFile.Position = 0;
while (csvReader.Read())
{
         var voucher = csvReader.GetRecord<VoucherFile>();
         vouchers.Add(voucher);
}
return Accepted(vouchers.Take(20));
```

**The exception sent :** 
```
CsvHelper.TypeConversion.CsvTypeConverterException: The conversion cannot be performed.
   at CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(TypeConverterOptions options, String text)
   at CsvHelper.TypeConversion.Int64Converter.ConvertFromString(TypeConverterOptions options, String text)
   at lambda_method(Closure )
   at CsvHelper.CsvReader.GetRecord[T]()
   at VoucherController.<VouchersFromVoucherFile>d__8.MoveNext() in Controllers\VoucherController.cs:line 181
```

**The exception.Data :** 
```
Row: '1' (1 based)
Type: 'myfile'
Field Index: '0' (0 based)
Field Value: '1;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;somestring;somestring'
```

When using a comma, a "|" or a "~", there is no exception sent and I get the ouput I want.

Does anyone know what could be causing this...? I have to say that I am a bit mystified...

**Update :** in case you need these informations, I am using CsvHelper 2.16.3 (installed through NuGet), ASP .NET Core 1.1.1 and ASP .NET Core MVC 1.1.2.

Thanks in advance :)

**Comment by jamesbascle** [comment]
Please also post the code for VoucherFileMap and VoucherFile classes.

**Comment by franelj** [comment]
Here they are : 

**VoucherFile class :** 
```
public class VoucherFile
    {
        [Required]
        public Int64? Id{ get; set; }

        [Required]
        public Currency? Currency { get; set; }

        [Required]
        public double NominalValue { get; set; }

        private DateTime? _voucherStartDate { get; set; }

        [Required]
        public DateTime? VoucherStartDate
        {
            get
            {
                return _voucherStartDate;
            }
            set
            {
                if (value != null)
                {
                    value = DateTime.SpecifyKind(value.Value, DateTimeKind.Local).ToUniversalTime();
                }
                _voucherStartDate = value;
            }
        }

        private DateTime? _voucherEndDate { get; set; }

        [Required]
        public DateTime? VoucherEndDate
        {
            get
            {
                return _voucherEndDate;
            }
            set
            {
                if (value != null)
                {
                    value = DateTime.SpecifyKind(value.Value, DateTimeKind.Local).ToUniversalTime();
                }
                _voucherEndDate = value;
            }
        }

        private DateTime? _activationEndDate { get; set; }

        public DateTime? ActivationEndDate
        {
            get
            {
                return _activationEndDate;
            }
            set
            {
                if (value != null)
                {
                    value = DateTime.SpecifyKind(value.Value, DateTimeKind.Local).ToUniversalTime();
                }
                _activationEndDate = value;
            }
        }

        [Required]
        [StringLength(20)]
        public string Ref { get; set; }

        [StringLength(20)]
        public string Variant { get; set; }
    }
```

**VoucherFileMap class :** 
```
public sealed class VoucherFileMap : CsvClassMap<VoucherFile>
    {
        public VoucherFileMap()
        {
            Map(m => m.Id).Index(0);
            Map(m => m.Currency).Index(1);
            Map(m => m.NominalValue).Index(2).TypeConverterOption(CultureInfo.InvariantCulture);
            Map(m => m.VoucherStartDate).Index(3).TypeConverterOption(DateTimeStyles.RoundtripKind);
            Map(m => m.VoucherEndDate).Index(4).TypeConverterOption(DateTimeStyles.RoundtripKind);
            Map(m => m.ActivationEndDate).Index(5).TypeConverterOption(DateTimeStyles.RoundtripKind);
            Map(m => m.Ref).Index(6);
            Map(m => m.Variant).Index(7);
        }
    }
```

**The sample (the lines are pretty much the same for now, only the id change) :** 
```
1;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
2;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
3;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
4;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
5;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
6;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
7;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
8;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
9;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
10;EUR;8.00;01-01-2017T00:00:00;31-12-2017T23:59:59;02-12-2017T12:12:34;reference;variant
```

**Comment by jamesbascle** [comment]
@JoshClose I think this could be .NET core related.  Except for some issues parsing the date times( which I suspect is due to the locale difference between myself and @franelj, and are adjusted in my screenshot), this parses correctly on my machine in LINQPad 5.  Unfortunately, I cannot test further as I've been having some issues having .NET core running properly on my machine.

![image](https://cloud.githubusercontent.com/assets/4188293/25390528/b98b2a82-29a1-11e7-8aed-d5298e0cd6e9.png)

**Comment by franelj** [comment]
Actually I think it could be a problem related to MemoryStream/StreamReader ? Because I just tested by commenting `MemoryStream vouchersFile = await blobClient.GetFileFromBlob("post", fileVoucherRequest.VoucherFilePath);` and replacing `TextReader tr = new StreamReader(vouchersFile);` by `TextReader tr = new StringReader() {...}` exactly like you did in your screenshot and it works even with semicolon. But I absolutely need to read data from a Stream so I am still stucked, and I also have no idea what in MemoryStream or StreamReader could cause this problem. Maybe some encoding differences between streams and strings? 

Also, the datetime parsing issue you had is my mistake, I inverted the month and the day in the second datetime when I wrote it in my comment. Sorry !

And about the `Currency?` type, it is an enum (with 3 values - EUR, USD and GBP) but I didn't need to use a custom converter, the EnumConverter seems to be enough to do the job.

**Comment by JoshClose** [comment]
I'm getting this when running it:

```
System.FormatException: 'The DateTime represented by the string is not supported in calendar System.Globalization.GregorianCalendar.'
```

**Comment by franelj** [comment]
@JoshClose ah, I did not correct my sample in my previous comment. Please use this one, it should work : 
```
1;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
2;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
3;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
4;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
5;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
6;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
7;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
8;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
9;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
10;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant
```

**Comment by JoshClose** [comment]
I created a .NETCoreApp 1.1 console project and this seems to work for me. Is there a discrepancy here?

```cs
using CsvHelper;
using CsvHelper.Configuration;
using System;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.IO;
using System.Linq;

namespace CsvHelperIssue674
{
    class Program
    {
        static void Main(string[] args)
        {
			using( var stream = new MemoryStream() )
			using( var writer = new StreamWriter( stream ) )
			using( var reader = new StreamReader( stream ) )
			using( var csv = new CsvReader( reader ) )
			{
				writer.WriteLine( "1;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "2;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "3;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "4;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "5;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "6;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "7;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "8;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "9;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.WriteLine( "10;EUR;8.00;2017-01-01T00:00:00;2017-12-31T23:59:59;2017-12-02T12:12:34;reference;variant" );
				writer.Flush();
				stream.Position = 0;

				csv.Configuration.Delimiter = ";";
				csv.Configuration.RegisterClassMap<VoucherFileMap>();
				csv.Configuration.HasHeaderRecord = false;
				var records = csv.GetRecords<VoucherFile>().ToList();

				Console.ReadKey();
			}
		}
    }

	public enum Currency
	{
		EUR,
		USD,
		GBP
	}

	public class VoucherFile
	{
		[Required]
		public Int64? Id { get; set; }

		[Required]
		public Currency? Currency { get; set; }

		[Required]
		public double NominalValue { get; set; }

		private DateTime? _voucherStartDate { get; set; }

		[Required]
		public DateTime? VoucherStartDate
		{
			get
			{
				return _voucherStartDate;
			}
			set
			{
				if( value != null )
				{
					value = DateTime.SpecifyKind( value.Value, DateTimeKind.Local ).ToUniversalTime();
				}
				_voucherStartDate = value;
			}
		}

		private DateTime? _voucherEndDate { get; set; }

		[Required]
		public DateTime? VoucherEndDate
		{
			get
			{
				return _voucherEndDate;
			}
			set
			{
				if( value != null )
				{
					value = DateTime.SpecifyKind( value.Value, DateTimeKind.Local ).ToUniversalTime();
				}
				_voucherEndDate = value;
			}
		}

		private DateTime? _activationEndDate { get; set; }

		public DateTime? ActivationEndDate
		{
			get
			{
				return _activationEndDate;
			}
			set
			{
				if( value != null )
				{
					value = DateTime.SpecifyKind( value.Value, DateTimeKind.Local ).ToUniversalTime();
				}
				_activationEndDate = value;
			}
		}

		[Required]
		[StringLength( 20 )]
		public string Ref { get; set; }

		[StringLength( 20 )]
		public string Variant { get; set; }
	}

	public sealed class VoucherFileMap : CsvClassMap<VoucherFile>
	{
		public VoucherFileMap()
		{
			Map( m => m.Id ).Index( 0 );
			Map( m => m.Currency ).Index( 1 );
			Map( m => m.NominalValue ).Index( 2 ).TypeConverterOption( CultureInfo.InvariantCulture );
			Map( m => m.VoucherStartDate ).Index( 3 ).TypeConverterOption( DateTimeStyles.RoundtripKind );
			Map( m => m.VoucherEndDate ).Index( 4 ).TypeConverterOption( DateTimeStyles.RoundtripKind );
			Map( m => m.ActivationEndDate ).Index( 5 ).TypeConverterOption( DateTimeStyles.RoundtripKind );
			Map( m => m.Ref ).Index( 6 );
			Map( m => m.Variant ).Index( 7 );
		}
	}

}
```

**Comment by franelj** [comment]
Okay, I just tried your code and it is working fine. I guess the problem is on my side - probably my file, its encoding or something else... I'll figure it out !

Thanks to both of you for your help though !

**Comment by JoshClose** [comment]
You're welcome!

If it's a different encoding or something, you'll need to set that on the stream. CsvHelper doesn't know anything about that.

Let me know if you have any other questions.
