### ISSUE TITLE
RegisterClassMap Throws NullReferenceException in Parallel.ForEach 

### ISSUE THREAD

**Issue by hakenmt** [JoshClose/CsvHelper#754]
This is the code I'm using:
```cs
    Parallel.ForEach(paths, Path => {
      using (StreamReader SReader = new StreamReader(Str))
      {
        using (CsvReader Reader = new CsvReader(SReader))
        {
          Reader.Configuration.RegisterClassMap<RawBillingItemMapping>();
        }
      }
    });
```

I occasionally get a NullReferenceException when calling RegisterClassMap which leads me to believe there's a race condition when inserting into an underlying dictionary. Here's the stack trace:

```
at System.Collections.Generic.Dictionary``2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at CsvHelper.ReflectionHelper.CreateInstanceWithoutContractResolver(Type type, Object[] args) in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\ReflectionHelper.cs:line 71
   at CsvHelper.ReflectionHelper.CreateInstance[T](Object[] args) in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\ReflectionHelper.cs:line 31
   at CsvHelper.Configuration.CsvConfiguration.RegisterClassMap[TMap]() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\Configuration\CsvConfiguration.cs:line 381
   at Class.<>c__DisplayClass29_0.<GetData>b__0(String Path) in C:\Class.cs:line 170
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0``2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
```

Can CsvHelper not be used to read different files in parallel when registering a class map?

**Comment by JoshClose** [comment]
This should be fixed in the latest pre-release. https://www.nuget.org/packages/CsvHelper/3.0.0-RC01
