### ISSUE TITLE
Parse error when using TrimOptions.Trim

### ISSUE THREAD

**Issue by CheeseSucker** [JoshClose/CsvHelper#761]
Some CSV files can not be parsed when TrimOptions.Trim is enabled.
See https://github.com/CheeseSucker/csv-trim-error for demonstration of this error.

Version: 3.0.0-RC02

```
{CsvHelper.ParserException: An unexpected error occurred. ---> System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.CtorCharArrayStartLength(Char[] value, Int32 startIndex, Int32 length)
   at CsvHelper.CsvFieldReader.AppendField() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvFieldReader.cs:line 200
   at CsvHelper.CsvFieldReader.GetField() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvFieldReader.cs:line 173
   at CsvHelper.CsvParser.ReadField() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvParser.cs:line 424
   at CsvHelper.CsvParser.ReadLine() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvParser.cs:line 206
   at CsvHelper.CsvParser.Read() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvParser.cs:line 90
   --- End of inner exception stack trace ---
   at CsvHelper.CsvParser.Read() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvParser.cs:line 96
   at CsvHelper.CsvReader.Read() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvReader.cs:line 195
   at CsvHelper.CsvReader.<GetRecords>d__62`1.MoveNext() in C:\Users\narsh\Projects\CsvHelper\src\CsvHelper\CsvReader.cs:line 1042
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at CsvBug.Program.ReadCsv(String content) in C:\git\CsvBug\CsvBug\Program.cs:line 40
   at CsvBug.Program.Main(String[] args) in C:\git\CsvBug\CsvBug\Program.cs:line 24}
```

**Comment by JoshClose** [comment]
c08cdaa237d2373755acbdf428c4bd36cab105e3
