### ISSUE TITLE
HasHeaderRecord / GetField<Type>("name") broke

### ISSUE THREAD

**Issue by rdons** [JoshClose/CsvHelper#777]
Just updated the NuGet package from version 2.16.3 to version 3 and left my user code in place. I noticed that atleast the `GetField<Type>("name")` method doesn't work anymore - well actually that's all I use to read the CSVs, so I don't know about the rest.

```
CsvHelper.MissingFieldException occurred
  HResult=0x80131500
  Message=Field with names ['Id'] at index '0' does not exist. You can ignore missing fields by setting MissingFieldFound to null.
  Source=CsvHelper
  StackTrace:
   at CsvHelper.Configuration.Configuration.<>c.<.ctor>b__148_2(String[] headerNames, Int32 index, IReadingContext context)
   at CsvHelper.CsvReader.GetFieldIndex(String[] names, Int32 index, Boolean isTryGet)
   at CsvHelper.CsvReader.GetField[T](String name, ITypeConverter converter)
   at CsvHelper.CsvReader.GetField[T](String name)
   at XXX.XXX.Data.Cosmos.Repository.Verifications.CosmosDataSeeder.CreateDataSet() in C:\Git\XXX\XXX.XXX.Data.Cosmos.Repository.Verifications\Repository\UserDataSeeder.cs:line 73
   at XXX.XXX.Data.Cosmos.Repository.Verifications.CosmosDataSeeder.<>c__DisplayClass4_0.<CreateCosmosDataSet>b__0() in C:\Git\XXX\XXX.XXX.Data.Cosmos.Repository.Verifications\Repository\UserDataSeeder.cs:line 39
   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)
```

According to the documentation the default setting for `HasHeaderRecord `is set to true. But even setting it manually to true does not resolve. When setting the `MissingFieldFound`, all I get are empty records, nothing gets populated.

According to the semver the update could lead to breaking changes, but according to documentation not a big deal. Interesting is that with my CSV of 1000 rows + 1 header row, I get 1001 data rows, which leads me to think something just broke here...

**Comment by JoshClose** [comment]
You need to read the header. This isn't done for you automatically anymore. The reason is you may want to read more things in the header. This just gives you more control. I'll update the documentation so this change is clear.

```cs
csv.Read();
csv.ReadHeader();
csv.Read();
csv.GetField<Type>( "name" );
```

**Comment by JoshClose** [comment]
Also, when writing `WriteHeader` doesn't call `NextRecord` anymore. I'll document that also.

**Comment by alectec** [comment]
Could ReaderHeader() still exist in it's current capacity but Read() automatically jump over the header if it's there?  It may be more clear this way.  Just a thought. :)

**Comment by JoshClose** [comment]
The concept is `Read` will pull the next record from the parser, then you are able to act on that record. If you have a header you can call `ReaderHeader`. You can also then do more things on the header row if you like. Sometimes people have headers on multiple rows.  There is a header followed by a bunch of rows, then another header followed by a different type of rows. This is another reason why that call is separate.

**Comment by dansharpe83** [comment]
i've just started having a similar issue and can't figure out why when i read my file, this is my map:
`Map(s => s.SPID).Name("SPID").Index(0);
            Map(s => s.WholesalerID).Name("Wholesaler ID").Index(1);
            Map(s => s.RetailerID).Name("Retailer ID").Index(2);
            Map(s => s.OtherWholesalerID).Name("Other Wholesaler ID").Index(3);
            Map(s => s.MultipleWholesalersFlag).Name("Multiple Wholesalers Flag").Index(4);
            Map(s => s.DisconnectionStatus).Name("Disconnection Status").Index(5);
            Map(s => s.VOABAReference).Name("VOA BA Reference").Index(6);
            Map(s => s.VOABAReferenceReasonCode).Name("VOA BA Reference Reason Code").Index(7);
            Map(s => s.UPRN).Name("UPRN").Index(8);
            Map(s => s.UPRNReasonCode).Name("UPRN Reason Code").Index(9);
            Map(s => s.CustomerClassificationSensitiveCustomer).Name("Customer Classification - Sensitive Customer").Index(10);
            Map(s => s.PublicHealthRelatedSiteSpecificArrangementsFlag).Name("Public Health Related Site Specific Arrangements Flag").Index(11);
            Map(s => s.NonPublicHealthRelatedSiteSpecificArrangementsFlag).Name("Non-Public Health Related Site Specific Arrangements Flag").Index(12);
            Map(s => s.NonPublicHealthRelatedSiteSpecificArrangementsFreeDescriptor).Name("Non-Public Health Related Site Specific Arrangements Free Descriptor").Index(13).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Non-Public Health Related Site Specific Arrangements Free Descriptor")));
            Map(s => s.StandardIndustrialClassificationCode).Name("Standard Industrial Classification Code").Index(14);
            Map(s => s.StandardIndustrialClassificationCodeType).Name("Standard Industrial Classification Code Type").Index(15);
            Map(s => s.RateableValue).Name("Rateable Value").Index(16);
            Map(s => s.OccupancyStatus).Name("Occupancy Status").Index(17);
            Map(s => s.BuildingWaterStatus).Name("Building Water Status").Index(18);
            Map(s => s.LandlordSPID).Name("Landlord SPID").Index(19);
            Map(s => s.Section154ADwellingUnits).Name("Section 154A Dwelling Units").Index(20);
            Map(s => s.CustomerName).Name("Customer Name").Index(21).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Customer Name")));
            Map(s => s.CustomerBannerName).Name("Customer Banner Name").Index(22).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Customer Banner Name")));
            Map(s => s.Address.FreeDescriptor).Name("Premises Address – Free Descriptor").Index(23).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Premises Address – Free Descriptor")));
            Map(s => s.Address.SecondaryAddressableObject).Name("Premises Address – Secondary Addressable Object").Index(24).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Premises Address – Secondary Addressable Object")));
            Map(s => s.Address.PrimaryAddressableObject).Name("Premises Address – Primary Addressable Object").Index(25).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Premises Address – Primary Addressable Object")));
            Map(s => s.Address.AddressLine1).Name("Premises Address – Address Line 1").Index(26).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Premises Address – Address Line 1")));
            Map(s => s.Address.AddressLine2).Name("Premises Address – Address Line 2").Index(27).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Premises Address – Address Line 2")));
            Map(s => s.Address.AddressLine3).Name("Premises Address – Address Line 3").Index(28).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Premises Address – Address Line 3")));
            Map(s => s.Address.AddressLine4).Name("Premises Address – Address Line 4").Index(29).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Premises Address – Address Line 4")));
            Map(s => s.Address.AddressLine5).Name("Premises Address – Address Line 5").Index(30).ConvertUsing(r => BaseFileParser.RemoveLineBreaks(r.GetField<string>("Premises Address – Address Line 5")));
            Map(s => s.Address.Postcode).Name("Premises Address - Postcode").Index(31);
            Map(s => s.Address.PAFAddressKey).Name("Premises Address – PAF Address Key").Index(32);
            Map(s => s.SupplyPointEffectiveFromDate).Name("Supply Point Effective From Date").Index(33).TypeConverterOption.Format("yyyy-MM-dd");
            Map(s => s.RegistrationStartDate).Name("Registration Start Date").Index(34).TypeConverterOption.Format("yyyy-MM-dd");
            Map(s => s.OtherServiceCategoryProvidedFlag).Name("Other Service Category Provided Flag").Index(35).TypeConverter<NullableBooleanTypeConverter>();
            Map(s => s.OtherServiceCategoryProvidedFlagReason).Name("Other Service Category Provided Flag Reason").Index(36);
            Map(s => s.VolumeTransferType).Name("Volume Transfer Type").Index(37);
            Map(s => s.InterimDutySupplyPointFlag).Name("Interim Duty Supply Point Flag").Index(38).TypeConverter<NullableBooleanTypeConverter>();`

it gives me this error on the first line of the file:
: 'Header matching ['Premises Address - Postcode'] names at index 0 was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.'

here is the file it's failing on:
[test-data.txt](https://github.com/JoshClose/CsvHelper/files/1924720/test-data.txt)

and to process it i do this:
`using (var textReader = File.OpenText(fullFilePath))
            {
                //skip the first line
                textReader.ReadLine();
                
                using (CsvHelper.CsvReader reader = new CsvHelper.CsvReader(textReader, config))
                {
                    //reader.Read();
                    //var headres = reader.ReadHeader();
                    meters = reader.GetRecords<T>().ToList();
                }
            }`

any idea why i would get this? in the exception detail i can see the record has the correct number of cells and they all line up where they should, the header also looks to be correct

**Comment by JoshClose** [comment]
Can you create a new issue an post your class along with this info?

**Comment by dansharpe83** [comment]
done: https://github.com/JoshClose/CsvHelper/issues/995
